# Generated by Django 4.0.5 on 2022-06-09 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialaccount',
            old_name='social_acccunt_id',
            new_name='social_account_id',
        ),
        migrations.RenameField(
            model_name='socialaccount',
            old_name='social_login',
            new_name='uesr',
        ),
    ]
