# Generated by Django 4.0.2 on 2022-06-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscription_user_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.ManyToManyField(through='users.Subscription', to='users.User'),
        ),
    ]
