# Generated by Django 4.0.2 on 2022-06-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_social_acccunt_id_socialaccount_social_account_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialaccount',
            old_name='uesr',
            new_name='user',
        ),
    ]
