# Generated by Django 4.0.2 on 2022-06-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_post_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='post',
            name='sub_title',
            field=models.CharField(default=1, max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_image',
            field=models.CharField(default=1, max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=1, max_length=150),
        ),
    ]
