# Generated by Django 4.0.5 on 2022-06-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscription_user_subscription_and_more'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='InterestedAuthor',
        ),
        migrations.AlterModelTable(
            name='interestedauthor',
            table='interested_authors',
        ),
    ]
