# Generated by Django 4.0.2 on 2022-06-15 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
        ('authors', '0003_author_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.subcategory'),
        ),
    ]
